# Generated by Django 3.0.3 on 2021-04-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20210420_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Course',
        ),
    ]
