# Generated by Django 3.0.3 on 2021-04-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.School'),
        ),
    ]
