# Generated by Django 3.0.3 on 2021-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.ManyToManyField(to='quiz.Subject'),
        ),
    ]
