# Generated by Django 3.0.3 on 2021-04-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_auto_20210420_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Subject'),
        ),
    ]
