# Generated by Django 3.0.3 on 2021-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_auto_20210420_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.ManyToManyField(blank=True, to='quiz.Subject'),
        ),
    ]
